on:
  pull_request:
    branches:
      - master

name: Lint all files

jobs:
  lints-editorconfig:
    name: Lint against .editorconfig
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check EditorConfig Compliance
        uses: editorconfig-checker/action-editorconfig-checker@v1

  lints:
    name: Lint all files
    runs-on: ubuntu-latest
    needs: [lints-editorconfig]
    steps:
     - run: echo "All lints successful"
